service: orbit-v1
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  dynamodb:
    stages:
      - staging
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  serverless-offline:
    noPrependStageInUrl: true
  table:
    VAULT_SNAPSHOTS_DATA: vaults-${self:custom.stage}

package:
  exclude:
    - node_modules/serverless*/**

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: dev
  region: us-east-1
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
  environment:
    # Table definitions
    VAULT_SNAPSHOTS_DATA: ${self:custom.table.VAULT_SNAPSHOTS_DATA}
    STAGE: ${self:custom.stage}

resources:
  Resources:
    vaultsSnapshotsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.VAULT_SNAPSHOTS_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: "address"
            KeyType: "HASH"
          - AttributeName: "createdAt"
            KeyType: "RANGE"
        AttributeDefinitions:
          - AttributeName: "address"
            AttributeType: "S"
          - AttributeName: "createdAt"
            AttributeType: "N"

functions:
  test:
    handler: app/handler.test
    events:
      - http:
          path: test
          method: get
  findVaults:
    handler: app/handler.findVaults
    events:
      - http:
          path: vaults
          method: get
  findOneVault:
    handler: app/handler.findOneVault
    events:
      - http:
          path: vaults/{id}
          method: get
  updateVaults:
    handler: app/handler.updateVaults
    events:
      - http:
          path: update/vaults
          method: get
      - schedule:
          name: ${self:service}-${self:custom.stage}-update-vaults-history
          description: "update historical data for all vaults"
          rate: rate(1 minute)
          enabled: true
