service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
    # DB_URL: ${DB_URL}
    # DB_NAME: ${DB_NAME}
    # DB_BOOKS_COLLECTION: ${DB_BOOKS_COLLECTION}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  findVaults:
    handler: app/handler.findVaults
    events:
      - http:
          path: vaults
          method: get
  updateVaults:
    handler: app/handler.updateVaults
    events:
      - http:
          path: update/vaults
          method: get
  # create:
  #   handler: app/handler.create
  #   events:
  #     - http:
  #         path: books
  #         method: post
  # update:
  #   handler: app/handler.update
  #   events:
  #     - http:
  #         path: books/{id}
  #         method: put
  # findOne:
  #   handler: app/handler.findOne
  #   events:
  #     - http:
  #         path: books/{id}
  #         method: get

  # deleteOne:
  #   handler: app/handler.deleteOne
  #   events:
  #     - http:
  #         path: books/{id}
  #         method: delete
